"""schedule_tag

Revision ID: 11c80bf28552
Revises: 3a5b5550d977
Create Date: 2015-07-08 22:28:16.935415

"""

# revision identifiers, used by Alembic.
revision = '11c80bf28552'
down_revision = '3a5b5550d977'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_tag',
    sa.Column('schedule_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('schedule_id', 'tag_id')
    )
    op.drop_column(u'schedule', 'tags')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'schedule', sa.Column('tags', mysql.VARCHAR(collation=u'utf8_polish_ci', length=4096), nullable=True))
    op.drop_table('schedule_tag')
    ### end Alembic commands ###
