"""operation_tag model

Revision ID: 2797eb8704a9
Revises: 50f1156d4119
Create Date: 2015-05-09 21:34:17.311268

"""

# revision identifiers, used by Alembic.
revision = '2797eb8704a9'
down_revision = '50f1156d4119'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_tag',
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('operation_id', 'tag_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_tag')
    ### end Alembic commands ###
