"""removed external from schedule

Revision ID: 3a5b5550d977
Revises: 3e6319111e71
Create Date: 2015-07-07 21:45:44.797967

"""

# revision identifiers, used by Alembic.
revision = '3a5b5550d977'
down_revision = '3e6319111e71'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'external')
    op.alter_column('schedule', 'account_2_id',
               existing_type=mysql.VARCHAR(collation=u'utf8_polish_ci', length=36),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'account_2_id',
               existing_type=mysql.VARCHAR(collation=u'utf8_polish_ci', length=36),
               nullable=False)
    op.add_column('schedule', sa.Column('external', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    ### end Alembic commands ###
