"""Renamed transacion_id into transfer_id

Revision ID: 3b963cbb3b3c
Revises: 8c5c0ed5c38
Create Date: 2015-06-21 13:18:06.696266

"""

# revision identifiers, used by Alembic.
revision = '3b963cbb3b3c'
down_revision = '8c5c0ed5c38'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('transfer_id', sa.String(length=36), nullable=True))
    op.drop_column('operation', 'transaction_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('transaction_id', mysql.VARCHAR(collation=u'utf8_polish_ci', length=36), nullable=True))
    op.drop_column('operation', 'transfer_id')
    ### end Alembic commands ###
