"""schedule, schedule_period

Revision ID: 3e6319111e71
Revises: 41160432ede1
Create Date: 2015-07-07 20:05:41.018583

"""

# revision identifiers, used by Alembic.
revision = '3e6319111e71'
down_revision = '41160432ede1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_period',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('schedule',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_1_id', sa.String(length=36), nullable=False),
    sa.Column('account_2_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('desc', sa.String(length=1024), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('schedule_period_id', sa.String(length=36), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('tags', sa.String(length=4096), nullable=True),
    sa.Column('external', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_1_id'], ['account.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['account_2_id'], ['account.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['schedule_period_id'], ['schedule_period.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    op.drop_table('schedule_period')
    ### end Alembic commands ###
