"""transfer_id -> id

Revision ID: 41160432ede1
Revises: 43fd3283b24a
Create Date: 2015-06-21 13:33:11.469679

"""

# revision identifiers, used by Alembic.
revision = '41160432ede1'
down_revision = '43fd3283b24a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('id', sa.String(length=36), nullable=False))
    op.drop_column('transfer', 'transfer_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('transfer_id', mysql.VARCHAR(collation=u'utf8_polish_ci', length=36), nullable=False))
    op.drop_column('transfer', 'id')
    ### end Alembic commands ###
