"""Added transfer table

Revision ID: 43fd3283b24a
Revises: 3b963cbb3b3c
Create Date: 2015-06-21 13:25:17.667507

"""

# revision identifiers, used by Alembic.
revision = '43fd3283b24a'
down_revision = '3b963cbb3b3c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer',
    sa.Column('transfer_id', sa.String(length=36), nullable=False),
    sa.Column('operation_from_id', sa.String(length=36), nullable=False),
    sa.Column('operation_to_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['operation_from_id'], ['operation.id'], ),
    sa.ForeignKeyConstraint(['operation_to_id'], ['operation.id'], ),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer')
    ### end Alembic commands ###
