"""operation model

Revision ID: 50f1156d4119
Revises: 1aed3873df91
Create Date: 2015-05-09 21:32:24.567883

"""

# revision identifiers, used by Alembic.
revision = '50f1156d4119'
down_revision = '1aed3873df91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('operation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('booked', sa.Boolean(), nullable=False),
    sa.Column('order_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_by')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    op.drop_table('tag')
    ### end Alembic commands ###
