"""order_by might be null

Revision ID: 8c5c0ed5c38
Revises: 2797eb8704a9
Create Date: 2015-05-10 22:41:16.389783

"""

# revision identifiers, used by Alembic.
revision = '8c5c0ed5c38'
down_revision = '2797eb8704a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('order_by', 'operation')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('order_by', 'operation', ['order_by'])
    ### end Alembic commands ###
